# Generated by Django 6.0.2 on 2026-02-20 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='preferred_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_candidates', to='positions.position'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['last_name', 'first_name'], name='candidates__last_na_35ea62_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['status'], name='candidates__status_0f124f_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['created_at'], name='candidates__created_a71da5_idx'),
        ),
    ]
