# Generated by Django 6.0.2 on 2026-02-22 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('in_review', 'In review'), ('interview', 'Interview'), ('offered', 'Offered'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='candidates.candidate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='positions.position')),
            ],
            options={
                'indexes': [models.Index(fields=['position', 'status'], name='recruitment_positio_a0697d_idx'), models.Index(fields=['candidate', 'status'], name='recruitment_candida_be1aae_idx')],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'position'), name='uniq_candidate_position_application')],
            },
        ),
    ]
