# Generated by Django 6.0.2 on 2026-02-20 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(max_length=255)),
                ('contract_type', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('interim', 'Interim'), ('other', 'Other')], default='other', max_length=20)),
                ('external_company_id', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PositionTemplatePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('soft', 'Soft skills'), ('hard', 'Hard skills'), ('full', 'Full evaluation')], default='full', max_length=10)),
                ('scope', models.CharField(choices=[('candidate', 'Candidate'), ('employee', 'Employee'), ('both', 'Both')], default='both', max_length=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('set_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_policies', to='positions.position')),
            ],
        ),
    ]
