# Generated by Django 6.0.2 on 2026-02-20 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0001_initial'),
        ('templates_grid', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='positiontemplatepolicy',
            name='set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_position_template_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='positiontemplatepolicy',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_policies', to='templates_grid.template'),
        ),
        migrations.AddIndex(
            model_name='positiontemplatepolicy',
            index=models.Index(fields=['position', 'stage', 'scope', 'is_active'], name='positions_p_positio_4c62ff_idx'),
        ),
        migrations.AddIndex(
            model_name='positiontemplatepolicy',
            index=models.Index(fields=['effective_from'], name='positions_p_effecti_9c0856_idx'),
        ),
        migrations.AddConstraint(
            model_name='positiontemplatepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('position', 'stage', 'scope'), name='uniq_active_policy_per_position_stage_scope'),
        ),
    ]
