# Generated by Django 6.0.2 on 2026-04-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_positiontesttemplateassignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='positiontesttemplateassignment',
            new_name='positions_p_positio_a033f0_idx',
            old_name='positions_po_57c7f0_idx',
        ),
        migrations.RenameIndex(
            model_name='positiontesttemplateassignment',
            new_name='positions_p_manager_898be3_idx',
            old_name='positions_ma_38c84f_idx',
        ),
    ]
