# Generated by Django 6.0.2 on 2026-02-20 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates_grid', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='templateversion',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_template_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templateversion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='templates_grid.template'),
        ),
        migrations.AddField(
            model_name='versionedpool',
            name='template_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='templates_grid.templateversion'),
        ),
        migrations.AddField(
            model_name='versionedquestion',
            name='versioned_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='templates_grid.versionedpool'),
        ),
        migrations.AddConstraint(
            model_name='templatepool',
            constraint=models.UniqueConstraint(fields=('template', 'pool'), name='uniq_pool_per_template'),
        ),
        migrations.AddConstraint(
            model_name='templateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version'), name='uniq_template_version'),
        ),
        migrations.AddIndex(
            model_name='versionedpool',
            index=models.Index(fields=['template_version', 'order'], name='templates_g_templat_2b1e63_idx'),
        ),
        migrations.AddIndex(
            model_name='versionedquestion',
            index=models.Index(fields=['versioned_pool', 'order'], name='templates_g_version_52a40b_idx'),
        ),
    ]
