# Generated by Django 6.0.2 on 2026-02-24 22:49
from django.db import migrations, models
from django.utils import timezone


def backfill_skillquestion_v2(apps, schema_editor):
    SkillQuestion = apps.get_model("templates_grid", "SkillQuestion")

    now = timezone.now()

    # Copy old label into new fields if present
    for q in SkillQuestion.objects.all().only("id"):
        # We must fetch dynamic fields safely (old migration state has them)
        q_obj = SkillQuestion.objects.get(id=q.id)

        label = getattr(q_obj, "label", "") or ""
        if not getattr(q_obj, "title", ""):
            q_obj.title = label[:255]
        if not getattr(q_obj, "text", ""):
            q_obj.text = label

        if getattr(q_obj, "created_at", None) is None:
            q_obj.created_at = now
        if getattr(q_obj, "updated_at", None) is None:
            q_obj.updated_at = now

        q_obj.save(update_fields=["title", "text", "created_at", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("templates_grid", "0001_initial"),
    ]

    operations = [
        # Keep your cleanup (constraint/index) if they exist in 0001
        migrations.RemoveConstraint(
            model_name="skillquestion",
            name="ck_question_min_le_max",
        ),
        migrations.RemoveIndex(
            model_name="skillquestion",
            name="templates_g_pool_id_418a1e_idx",
        ),

        # ✅ Add new fields as NULLABLE (no broken defaults)
        migrations.AddField(
            model_name="skillquestion",
            name="created_at",
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="skillquestion",
            name="updated_at",
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="skillquestion",
            name="format",
            field=models.CharField(
                choices=[("mcq", "Multiple Choice"), ("true_false", "True/False"), ("practical", "Practical")],
                default="mcq",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="skillquestion",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("intermediate", "Intermediate"), ("hard", "Hard")],
                default="intermediate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="skillquestion",
            name="points",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="skillquestion",
            name="title",
            field=models.CharField(max_length=255, blank=True, default=""),
        ),
        migrations.AddField(
            model_name="skillquestion",
            name="text",
            field=models.TextField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="skillquestion",
            name="explanation",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="skillquestion",
            name="rubric",
            field=models.JSONField(blank=True, default=dict),
        ),

        # ✅ Backfill from legacy fields
        migrations.RunPython(backfill_skillquestion_v2, migrations.RunPython.noop),
    ]