# Generated by Django 6.0.2 on 2026-05-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates_grid", "0005_extend_skillquestion_formats"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillquestion",
            name="is_eliminatory",
            field=models.BooleanField(default=False),
        ),
    ]
