# Generated by Django 6.0.2 on 2026-02-20 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='positions.position'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name', 'first_name'], name='employees_e_last_na_99a4c0_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_number'], name='employees_e_employe_e7cf1b_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['created_at'], name='employees_e_created_52c8e7_idx'),
        ),
    ]
