# Generated by Django 6.0.2 on 2026-04-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'Human Resources'), ('manager', 'Manager'), ('director', 'Director'), ('driver', 'Driver'), ('candidate', 'Candidate'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
