# Generated by Django 6.0.2 on 2026-02-22 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0001_initial'),
        ('recruitment', '0001_initial'),
        ('templates_grid', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('validated', 'Validated')], default='in_progress', max_length=20)),
                ('subject_comment', models.TextField(blank=True)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='recruitment.jobapplication')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_evaluations', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='positions.position')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='templates_grid.templateversion')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_visible_to_subject', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='evaluations.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evaluations.evaluation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_questions', to='templates_grid.versionedquestion')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_questions', to='templates_grid.versionedsection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationSectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_assignments', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_assignments', to='evaluations.evaluation')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='templates_grid.versionedsection')),
            ],
        ),
        migrations.CreateModel(
            name='SkillAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='evaluations.evaluationquestion')),
            ],
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['status', 'created_at'], name='evaluations_status_1044bd_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['subject', 'created_at'], name='evaluations_subject_43bd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['position', 'created_at'], name='evaluations_positio_4aef7d_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationcomment',
            index=models.Index(fields=['evaluation', 'created_at'], name='evaluations_evaluat_148c86_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationcomment',
            index=models.Index(fields=['is_visible_to_subject'], name='evaluations_is_visi_d2adc2_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationquestion',
            index=models.Index(fields=['evaluation', 'order'], name='evaluations_evaluat_c036a7_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationquestion',
            index=models.Index(fields=['section', 'order'], name='evaluations_section_5c4996_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluationquestion',
            constraint=models.UniqueConstraint(fields=('evaluation', 'question'), name='uniq_eval_question'),
        ),
        migrations.AddIndex(
            model_name='evaluationsectionassignment',
            index=models.Index(fields=['assigned_to'], name='evaluations_assigne_388e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationsectionassignment',
            index=models.Index(fields=['evaluation'], name='evaluations_evaluat_7668e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluationsectionassignment',
            constraint=models.UniqueConstraint(fields=('evaluation', 'section'), name='uniq_eval_section_assignment'),
        ),
        migrations.AddIndex(
            model_name='skillanswer',
            index=models.Index(fields=['created_at'], name='evaluations_created_1fbf24_idx'),
        ),
    ]
