# Generated by Django 6.0.2 on 2026-02-20 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0002_initial'),
        ('employees', '0002_initial'),
        ('evaluations', '0001_initial'),
        ('positions', '0001_initial'),
        ('templates_grid', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='positions.position'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='template_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='templates_grid.templateversion'),
        ),
        migrations.AddField(
            model_name='skillanswer',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_answers', to='evaluations.evaluation'),
        ),
        migrations.AddField(
            model_name='skillanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='templates_grid.versionedquestion'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['status', 'created_at'], name='evaluations_status_1044bd_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['position', 'created_at'], name='evaluations_positio_4aef7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('candidate__isnull', False), ('employee__isnull', True)), models.Q(('candidate__isnull', True), ('employee__isnull', False)), _connector='OR'), name='chk_exactly_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='skillanswer',
            constraint=models.UniqueConstraint(fields=('evaluation', 'question'), name='uniq_answer_per_eval_question'),
        ),
    ]
